package Shapes.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Canvas = 0;
  public static final int Circle = 1;
  public static final int Color = 2;
  public static final int ColorReference = 3;
  public static final int Shape = 4;
  public static final int Square = 5;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xb2221ba7a9454821L, 0xa8a492feb564c230L);
    builder.put(0x88c4fd1cffdf26dL, Canvas);
    builder.put(0x88c4fd1cffdf251L, Circle);
    builder.put(0x88c4fd1cffe8c8cL, Color);
    builder.put(0x88c4fd1cffebd05L, ColorReference);
    builder.put(0x88c4fd1cffdf250L, Shape);
    builder.put(0x88c4fd1cffdf263L, Square);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
